/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as InstructorsRouteImport } from './routes/instructors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/instructors': typeof InstructorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/instructors': typeof InstructorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/instructors': typeof InstructorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/classes' | '/dashboard' | '/gallery' | '/instructors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/classes' | '/dashboard' | '/gallery' | '/instructors'
  id: '__root__' | '/' | '/classes' | '/dashboard' | '/gallery' | '/instructors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassesRoute: typeof ClassesRoute
  DashboardRoute: typeof DashboardRoute
  GalleryRoute: typeof GalleryRoute
  InstructorsRoute: typeof InstructorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassesRoute: ClassesRoute,
  DashboardRoute: DashboardRoute,
  GalleryRoute: GalleryRoute,
  InstructorsRoute: InstructorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
